name: ci

on: [push, pull_request]

jobs:
  setup_matrix:
    name: "Setup Test Matrix"
    runs-on: ubuntu-latest
    outputs:
      spec_matrix: ${{ steps.get-matrix.outputs.spec_matrix }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      if: ${{ github.repository_owner == 'puppetlabs' }}

    - name: Activate Ruby 3.1
      uses: ruby/setup-ruby@v1
      if: ${{ github.repository_owner == 'puppetlabs' }}
      with:
        ruby-version: "3.1"
        bundler-cache: true

    - name: Print bundle environment
      if: ${{ github.repository_owner == 'puppetlabs' }}
      run: |
        echo ::group::bundler environment
        bundle env
        echo ::endgroup::
    - name: Setup Spec Test Matrix
      id: get-matrix
      if: ${{ github.repository_owner == 'puppetlabs' }}
      run: |
          bundle exec matrix_from_metadata_v3

  Spec:
    name: "Spec Tests (Puppet: ${{matrix.puppet_version}}, Ruby Ver: ${{matrix.ruby_version}})"
    needs:
      - setup_matrix
    if: ${{ needs.setup_matrix.outputs.spec_matrix != '{}' }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup_matrix.outputs.spec_matrix)}}

    env:
      PUPPET_GEM_VERSION: ${{ matrix.puppet_version }}
      FACTER_GEM_VERSION: 'https://github.com/puppetlabs/facter#main'

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: "Activate Ruby ${{ matrix.ruby_version }}"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby_version}}
        bundler-cache: true

    - name: Print bundle environment
      run: |
        echo ::group::bundler environment
        bundle env
        echo ::endgroup::
    - name: Run Static & Syntax Tests
      if: ${{ github.repository_owner == 'puppetlabs' }}
      run: |
        bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
    - name: Run parallel_spec tests
      run: |
        bundle exec rake parallel_spec
